version: '3'
services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nacos
      MYSQL_USER: nacos_query
      MYSQL_PASSWORD: query_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      internal:
        ipv4_address: 172.18.0.2

  nacos:
    image: nacos/nacos-server:v2.0.4
    ports:
      - "8848:8848"
    depends_on:
      - mysql
    entrypoint: ["sh", "-c", "while ! mysqladmin ping -hmysql -uroot -p123456 --silent; do sleep 1; done && mysql -hmysql -uroot -p123456 < /docker-entrypoint-initdb.d/nacos-init.sql && /startup.sh"]
    volumes:
      - ./nacos-init.sql:/docker-entrypoint-initdb.d/nacos-init.sql
    networks:
      internal:
        ipv4_address: 172.18.0.3

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1