version: '3.8'
services:
  namesrv:
    image: apache/rocketmq:4.9.2
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./rmqs/logs:/home/rocketmq/logs
    restart: always
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms256M -Xmx256M -Xmn128m"
    command: ["sh","mqnamesrv"]

  broker:
    image: apache/rocketmq:4.9.2
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./rmq/logs:/home/rocketmq/logs
      - ./rmq/store:/home/rocketmq/store
      - ./rmq/brokerconf/broker.conf:/etc/rocketmq/broker.conf
    links:
      - rmqnamesrv:namesrv
    depends_on:
      - 'namesrv'
    restart: always
    environment:
      NAMESRV_ADDR: namesrv:9876
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms256M -Xmx256M -Xmn128m"
    command: ["sh","mqbroker","-c","/home/rocketmq/broker.conf","autoCreateTopicEnable=true"]

  dashbord:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    ports:
      - 9880:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876"
    restart: always

